### ISSUE TITLE
[Question] File Upload Acceptance

### ISSUE THREAD

**Issue by sdr0x07b6** [apollo-server-integrations/apollo-server-integration-h3#44]
When using `startServerAndCreateH3Handler()` to accept GraphQL requests, can I handle file uploads with multipart data?

**Comment by tobiasdiez** [comment]
Using multipart is not really recommended by apollo, see https://www.apollographql.com/blog/backend/file-uploads/file-upload-best-practices/. But if you want to do it nonetheless, have a look at the graphql-upload package and in particular the koa middleware should give you a good starting point for the h3 implementation. If you go along this path, it would be nice if you could share your implementation in the form of a PR against the graphql-upload repo.
