### ISSUE TITLE
Activate rennovate bot

### ISSUE THREAD

**Issue by tobiasdiez** [apollo-server-integrations/apollo-server-integration-h3#7]
@trevor-scheer could you please activate rennovate for this repo. Since this since to be configured on the org level, I don't have the necessary rights to do so. Thanks!

**Comment by trevor-scheer** [comment]
Approved! Also added `renovate-approve` in case you'd like to require PR approvals for merging to allow renovate to automerge certain PRs. If you want to but can't disable it let me know.

**Comment by tobiasdiez** [comment]
Thanks a lot!
